#!/usr/bin/env python3
from __future__ import annotations

import json
import random
from typing import Any

from scripts.mutation_proposals import MutationProposal
from utils.ga_block_model import get_core_blocks, get_optional_blocks, normalize_active_blocks, validate_genome_blocks
from utils.pipeline_common import seeded_uuid


FAMILY_RATIOS = {
    "ACCURACY_SEARCH": {
        "accuracy_repair": 0.60,
        "temporal_reasoning": 0.15,
        "diversity": 0.15,
        "compression": 0.10,
    },
    "ROBUSTNESS_STABILIZATION": {
        "accuracy_repair": 0.35,
        "temporal_reasoning": 0.20,
        "regression_repair": 0.15,
        "compression": 0.20,
        "diversity": 0.10,
    },
    "COMPRESSION_SEARCH": {
        "compression": 0.45,
        "diversity": 0.20,
        "regression_repair": 0.15,
        "accuracy_repair": 0.10,
        "temporal_reasoning": 0.10,
    },
    "DISRUPTIVE_SEARCH": {
        "compression": 0.35,
        "diversity": 0.35,
        "accuracy_repair": 0.15,
        "temporal_reasoning": 0.15,
    },
}


def mutation_family_for_phase(phase: str, rng: random.Random) -> str:
    ratios = FAMILY_RATIOS.get(str(phase or "ACCURACY_SEARCH"), FAMILY_RATIOS["ACCURACY_SEARCH"])
    roll = rng.random()
    cumulative = 0.0
    for family, weight in ratios.items():
        cumulative += weight
        if roll <= cumulative:
            return family
    return next(iter(ratios))


def proposal_for_family(
    *,
    family: str,
    generation: int,
    parent_genome_id: str,
    feedback_hint: dict[str, Any] | None = None,
    rng: random.Random,
) -> MutationProposal:
    if family == "compression":
        operator = rng.choice(
            [
                "drop_optional_block",
                "reduce_few_shot_count",
                "merge_duplicate_micro_rules",
                "reduce_candidate_strategies",
                "compact_reasoning_skeleton",
                "lower_output_max_tokens",
            ]
        )
    elif family == "temporal_reasoning":
        operator = "activate_temporal_skeleton"
    elif family == "diversity":
        operator = rng.choice(["layout_shuffle", "block_variant_switch", "random_compact_seed"])
    elif family == "specialist":
        operator = rng.choice(["basic_compact_prompt", "temporal_skeleton_prompt", "complex_state_machine_prompt"])
    elif family == "regression_repair":
        operator = "restore_regression_safe_rule"
    else:
        operator = str((feedback_hint or {}).get("suggested_mutation_type") or "add_micro_rule")
    return MutationProposal(
        proposal_id=f"{family}_g{generation:03d}_{seeded_uuid(rng)[:8]}",
        source="det_feedback" if feedback_hint else "cloudless",
        mutation_family=family,
        operator=operator,
        target_block_id=str((feedback_hint or {}).get("prompt_block_id", "")),
        target_block_family=str((feedback_hint or {}).get("affected_block_family", "")),
        replacement_text=str((feedback_hint or {}).get("rule", "")),
        risk_score=0.35 if family == "compression" else 0.2,
        affected_failure_families=[str((feedback_hint or {}).get("failure_type", ""))] if feedback_hint else [],
        expected_effect=f"{family} mutation generated by phase-aware scheduler.",
        generation=generation,
        parent_genome_id=parent_genome_id,
    )


def apply_mutation_proposal(
    genome: dict[str, Any],
    proposal: MutationProposal,
    *,
    rng: random.Random,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    before = json.loads(json.dumps(genome, ensure_ascii=False))
    child = json.loads(json.dumps(genome, ensure_ascii=False))
    child["id"] = f"gen-{seeded_uuid(rng)}"
    child["seed"] = rng.randint(1, 10**9)
    child.setdefault("params", {})
    child.setdefault("block_params", {})
    child.setdefault("blocks", get_core_blocks())
    optional = [block for block in child.get("blocks", []) if block in get_optional_blocks()]
    operator = proposal.operator
    if operator in {"drop_optional_block", "drop_optional_blocks_for_budget"} and optional:
        removable = [block for block in optional if block not in {"03"}]
        target = removable[0] if removable else optional[-1]
        child["blocks"] = normalize_active_blocks([block for block in child.get("blocks", []) if block != target])
    elif operator in {"reduce_few_shot_count", "few_shot_reduction"}:
        block = child["block_params"].setdefault("02", {})
        before_count = int(block.get("few_shot_count", 2) or 2)
        block["few_shot_count"] = max(0, before_count - 1)
    elif operator in {"merge_duplicate_micro_rules", "prune_stale_micro_rules", "template_compress_rule_family"}:
        for block_id, params in child["block_params"].items():
            rules = list(params.get("micro_rules") or [])
            deduped = []
            seen = set()
            for rule in rules:
                key = " ".join(str(rule).lower().split())
                if key in seen:
                    continue
                seen.add(key)
                deduped.append(str(rule).strip())
            params["micro_rules"] = deduped[:4]
    elif operator == "reduce_candidate_strategies":
        strategies = list(child["params"].get("candidate_strategies") or [])
        child["params"]["candidate_strategies"] = strategies[: max(1, min(2, len(strategies)))] or ["direct"]
    elif operator in {"lower_output_max_tokens", "lower_max_tokens"}:
        child["params"]["max_tokens"] = min(int(child["params"].get("max_tokens", 768) or 768), 512)
    elif operator in {"activate_temporal_skeleton", "strengthen_temporal_rule"}:
        blocks = list(child.get("blocks", []))
        if "06" not in blocks:
            blocks.append("06")
        child["blocks"] = normalize_active_blocks(blocks)
        rules = child["block_params"].setdefault("06", {}).setdefault("micro_rules", [])
        rule = "Use compact skeleton: trigger -> delay/repeat -> guard -> action -> termination."
        if rule not in rules:
            rules.append(rule)
    elif operator in {"layout_shuffle", "block_variant_switch", "random_compact_seed"}:
        child["params"]["layout_mode"] = rng.choice(["schema_task_output", "output_first", "temporal_first", "skeleton_first"])
    elif proposal.replacement_text:
        block_id = proposal.target_block_id if proposal.target_block_id in {"02", "03", "06"} else "02"
        rules = child["block_params"].setdefault(block_id, {}).setdefault("micro_rules", [])
        if proposal.replacement_text not in rules:
            rules.append(proposal.replacement_text)
    child.setdefault("_ga_metadata", {})
    child["_ga_metadata"].update(
        {
            "parent_ids": [proposal.parent_genome_id or str(genome.get("id", ""))],
            "mutation_types": [operator],
            "mutation_family": proposal.mutation_family,
            "mutation_operator": operator,
            "mutation_proposal_id": proposal.proposal_id,
            "base_genome_id": proposal.parent_genome_id or str(genome.get("id", "")),
        }
    )
    child = validate_genome_blocks(child)
    diffs = _diff(before, child, proposal)
    child["_ga_metadata"]["diffs"] = diffs
    return child, diffs


def _diff(before: dict[str, Any], after: dict[str, Any], proposal: MutationProposal) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    fields = [
        ("blocks", before.get("blocks"), after.get("blocks")),
        ("params", before.get("params"), after.get("params")),
        ("block_params", before.get("block_params"), after.get("block_params")),
    ]
    for field, old, new in fields:
        if old != new:
            rows.append(
                {
                    "block_id": proposal.target_block_id or "genome",
                    "field": field,
                    "old_value": json.dumps(old, ensure_ascii=False, sort_keys=True),
                    "new_value": json.dumps(new, ensure_ascii=False, sort_keys=True),
                    "mutation_type": proposal.operator,
                    "mutation_family": proposal.mutation_family,
                    "feedback_driven": proposal.source in {"det_feedback", "advisor"},
                    "llm_advised": proposal.source == "advisor",
                    "advisor_proposal_id": proposal.advisor_proposal_id or (proposal.proposal_id if proposal.source == "advisor" else ""),
                    "advisor_batch_id": proposal.advisor_batch_id if proposal.source == "advisor" else "",
                    "failure_type_source": "|".join(proposal.affected_failure_families),
                }
            )
    return rows
